# Prometheus 监控配置
# 德国利息计算器应用监控设置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'zinses-rechner'
    environment: 'production'

# 规则文件
rule_files:
  - "rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # 前端应用监控
  - job_name: 'zinses-rechner-frontend'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: frontend:80

  # 后端API监控
  - job_name: 'zinses-rechner-backend'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    basic_auth:
      username: 'prometheus'
      password: 'monitoring_password'

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    params:
      format: ['prometheus']

  # Node Exporter (系统指标)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '${1}'

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    params:
      target: ['redis:6379']

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # 黑盒监控 (外部服务可用性)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://zinses-rechner.de
        - https://api.zinses-rechner.de/health
        - https://api.ecb.europa.eu/v1
        - https://api.bundesbank.de/bbk
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # 应用性能监控 (APM)
  - job_name: 'apm'
    static_configs:
      - targets: ['apm-server:8200']
    scrape_interval: 30s
    metrics_path: /metrics

  # 自定义业务指标
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 60s
    metrics_path: /business-metrics
    honor_labels: true

# 远程写入配置 (可选)
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    basic_auth:
      username: "remote_write_user"
      password: "remote_write_password"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'zinses_.*'
        action: keep

# 远程读取配置 (可选)
remote_read:
  - url: "https://prometheus-remote-read.example.com/api/v1/read"
    basic_auth:
      username: "remote_read_user"
      password: "remote_read_password"

# 存储配置
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true
